ci: .shippable.yml: add checkpatch
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

diff --git a/.shippable.yml b/.shippable.yml
--- a/.shippable.yml
+++ b/.shippable.yml
@@ -15,6 +15,26 @@ build:
     - export CROSS_COMPILE64="ccache aarch64-linux-gnu-"
     - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/.ccache
     - function _make() { make -j$(getconf _NPROCESSORS_ONLN) -s $*; ccache -s; ccache -z; }
+
+    # Download the Linux checkpatch tool
+    - >
+      mkdir ${SHIPPABLE_BUILD_DIR}/checkpatch &&
+      cd ${SHIPPABLE_BUILD_DIR}/checkpatch &&
+      wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl &&
+      chmod a+x checkpatch.pl &&
+      wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt &&
+      echo "invalid.struct.name" >const_structs.checkpatch &&
+      export PATH=${SHIPPABLE_BUILD_DIR}/checkpatch:${PATH} &&
+      source ${SHIPPABLE_BUILD_DIR}/scripts/checkpatch_inc.sh;
+    # Run checkpatch on:
+    # - the tip of the branch if we're not in a pull request
+    # - each commit in the development branch that's not in the target branch otherwise
+    - cd ${SHIPPABLE_BUILD_DIR}
+    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then checkpatch HEAD; else for c in $(git rev-list HEAD^1..HEAD^2); do checkpatch $c || failed=1; done; [ -z "$failed" ]; fi
+    # If we have a pull request with more than 1 commit, also check the squashed commits
+    # Useful to check if fix-up commits do indeed solve previous checkpatch errors
+    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then if [ "$(git rev-list --count HEAD^1..HEAD^2)" -gt 1 ]; then checkdiff $(git rev-parse HEAD^1) $(git rev-parse HEAD^2); fi; fi
+
 #    - ccache -z
 #    - _make
 #    - _make CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=1
@@ -100,11 +120,14 @@ build:
 #    - _make PLATFORM=rcar CFG_ARM64_core=y
 #    - _make PLATFORM=rpi3
 #    - _make PLATFORM=rpi3 CFG_ARM64_core=y
+
+    # Download Google's repo script
     - >
       mkdir -p ${SHIPPABLE_BUILD_DIR}/bin &&
       export PATH=${SHIPPABLE_BUILD_DIR}/bin:${PATH} &&
       curl https://storage.googleapis.com/git-repo-downloads/repo >${SHIPPABLE_BUILD_DIR}/bin/repo &&
       chmod +x ${SHIPPABLE_BUILD_DIR}/bin/repo;
+    # Clone the OP-TEE CI environment for QEMU and link optee_os to the current checkout
     - >
       mkdir -p ${SHIPPABLE_BUILD_DIR}/optee_repo_qemu &&
       cd ${SHIPPABLE_BUILD_DIR}/optee_repo_qemu &&
@@ -114,11 +137,12 @@ build:
       git submodule update --init dtc &&
       rm -rf ${SHIPPABLE_BUILD_DIR}/optee_repo_qemu/optee_os &&
       ln -s ${SHIPPABLE_BUILD_DIR} ${SHIPPABLE_BUILD_DIR}/optee_repo_qemu/optee_os;
+    # Run regression tests in QEMU
     - >
       cd ${SHIPPABLE_BUILD_DIR}/optee_repo_qemu/build &&
       unset CC &&
       make -k clean 2>&1 >/dev/null &&
       ccache -z &&
       make -j$(getconf _NPROCESSORS_ONLN) check CROSS_COMPILE="ccache arm-linux-gnueabihf-" AARCH32_CROSS_COMPILE=arm-linux-gnueabihf- DUMP_LOGS_ON_ERROR=1 &&
-      ccache -s
+      ccache -s &&
       make -k clean 2>&1 >/dev/null
